# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"WelcomeTab": "01_welcome.ipynb",
         "logger": "logger.ipynb",
         "DATA_DIR": "02_data.ipynb",
         "DATA_FILE": "02_data.ipynb",
         "DOWNLOAD_DATA_NAME": "02_data.ipynb",
         "FLOAT_FORMAT": "02_data.ipynb",
         "FILENAME": "02_data.ipynb",
         "DataModel": "02_data.ipynb",
         "DataView": "02_data.ipynb",
         "DataDelegate": "02_data.ipynb",
         "DataTab": "02_data.ipynb",
         "CRITERIA_TITLE": "03_selection.ipynb",
         "CRITERIA_APPLY": "03_selection.ipynb",
         "OUTPUT_TITLE": "03_selection.ipynb",
         "OUTPUT_PRE": "03_selection.ipynb",
         "OUTPUT_POST": "03_selection.ipynb",
         "EXPORT_TITLE": "03_selection.ipynb",
         "EXPORT_BUTTON": "03_selection.ipynb",
         "START_YEAR": "03_selection.ipynb",
         "END_YEAR": "03_selection.ipynb",
         "EXPORT_LINK_PROMPT": "03_selection.ipynb",
         "FilterView": "03_selection.ipynb",
         "FilterDelegate": "03_selection.ipynb",
         "ResultsDelegate": "03_selection.ipynb",
         "ExportView": "03_selection.ipynb",
         "ExportDelegate": "03_selection.ipynb",
         "SelectionTab": "03_selection.ipynb",
         "Main": "06_main.ipynb",
         "ConfigModel": "logger.ipynb",
         "CONFIG": "logger.ipynb",
         "SettingsModel": "logger.ipynb",
         "DispatchingFormatter": "logger.ipynb",
         "FORMATTER": "logger.ipynb",
         "ROOT_LOGGER": "logger.ipynb",
         "FILE_HANDLER": "logger.ipynb",
         "WidgetHandler": "logger.ipynb",
         "WIDGET_HANDLER": "logger.ipynb",
         "getLogger": "logger.ipynb"}

modules = ["welcome.py",
           "data.py",
           "selection.py",
           "main.py",
           "logger.py"]

doc_url = "https://nicole-brewer.github.io/template_lib/"

git_url = "https://github.com/nicole-brewer/template_lib/tree/main/"

def custom_doc_links(name): return None
