# AUTOGENERATED! DO NOT EDIT! File to edit: template_nbs/06_main.ipynb (unless otherwise specified).

__all__ = ['Main']

# Cell
import ipywidgets as widgets
from .welcome import WelcomeTab
from .data import DataModel, DataTab, FILENAME
from .selection import SelectionTab

# Cell
class Main(widgets.Tab):

    def __init__(self):
        super().__init__()

        # initialize models
        self.model = DataModel(FILENAME)

        # initialize views
        self.welcome = WelcomeTab()
        self.data = DataTab(self.model)
        self.selection = SelectionTab(self.model)

        self.children = (self.welcome, self.data, self.selection)

        self.set_title(0, 'Welcome')
        self.set_title(1, 'Data')
        self.set_title(2, 'Selection')