# AUTOGENERATED! DO NOT EDIT! File to edit: template_nbs/01_welcome.ipynb (unless otherwise specified).

__all__ = ['WelcomeTab']

# Cell
import ipywidgets as widgets

# Cell
class WelcomeTab(widgets.VBox):

    def __init__(self):
        # If you forget to call the superconstructor on an extended widget
        # you will get an AttributeError: object has no attribute '_model_id'
        super().__init__()

        # Using Accordion
        # Create accordion containing HTML content
        self.using_acc = widgets.Accordion()
        self.using_acc.set_title(0, 'Using this App')
        USING_TEXT = '''<p>
            In the <b>Data</b> tab above, you can review the dataset.
            In the <b>Selection</b> tab, you can search for and download data of interest.
            Once you've selected data, generate plots in the <b>Visualize</b> tab.
            </p>'''
        self.using_body = widgets.HTML(USING_TEXT)
        self.using_acc.children = (self.using_body, )

        # Data Souces Accordion
        # Create accordion containing HTML content
        self.sources_acc = widgets.Accordion()
        self.sources_acc.set_title(0, 'Data Sources')
        SOURCES_TEXT = '''<p>
            <b>Land-Ocean Temperature Index</b>
            <a href="https://climate.nasa.gov/vital-signs/global-temperature/"
            target="_blank">Global Temperature (NASA)</a>
            ,
            <a href="https://data.giss.nasa.gov/gistemp/"
            target="_blank">GISS Surface Temperature Analysis (NASA)</a>
            </p><p>
            This site is based on data downloaded from the following site on 2020-07-14:
            <a href="https://data.giss.nasa.gov/gistemp/graphs/graph_data/Global_Mean_Estimates_based_on_Land_and_Ocean_Data/graph.txt"  # noqa
            target="_blank">Global Mean Estimates based on Land_and Ocean Data (NASA)</a>
            </p>'''
        self.sources_body = widgets.HTML(SOURCES_TEXT)
        self.sources_acc.children = (self.sources_body, )

        self.children = (self.using_acc, self.sources_acc)