version: "3"
services:
  fastai: &fastai
    restart: "no"
    working_dir: /data
    image: fastai/codespaces
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    volumes:
      - .:/data/

  notebook:
    <<: *fastai
    command: bash -c "pip install -e . && jupyter notebook --allow-root --no-browser --ip=0.0.0.0 --port=8080 --NotebookApp.token='' --NotebookApp.password=''"
    ports:
      - "8080:8080"

  watcher:
    <<: *fastai
    command: watchmedo shell-command --command nbdev_build_docs --pattern *.ipynb --recursive --drop
    network_mode: host # for GitHub Codespaces https://github.com/features/codespaces/

  jekyll:
    <<: *fastai
    ports:
     - "4000:4000"
    command: >
     bash -c "pip install .
     && nbdev_build_docs && cd docs
     && bundle i
     && chmod -R u+rwx . && bundle exec jekyll serve --host 0.0.0.0"

  jupyterlab: &jupyterlab
    build: .
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work

  voila:
    <<: *jupyterlab
    expose:
      - 8866
      - 8888
    ports:
      - 8866:8866
      - 8888:8888
    command:  bash -c "voila /home/jovyan/work/APP.ipynb --no-browser"
    working_dir: /home/jovyan/voila
