FROM jupyter/scipy-notebook
LABEL maintainer="@brewer36"
ARG repourl

# This dockerfile is only meant to be used to deploy standalone web applications
# on cloud servers. Use docker-compose for development features.

# install packages we need for deploying the standalone app with Voila
RUN mamba install -c conda-forge voila jupyterthemes

WORKDIR "/home/${NB_USER}/work"

# setup git repo
RUN git clone --depth 1 $repourl work

# install any user packages defined in environment.yml
COPY environment.yml .
RUN mamba env update --file environment.yml

# start voila server
CMD ["voila","notebook.ipynb","--no-browser","--Voila.ip","0.0.0.0"]
