name: nbdev-application
channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupyterthemes
  - matplotlib
  - pandas
  - python=3.8
  - voila
  - jupyter
  - notebook
  - nbdev
